#!/bin/sh

BUILD_TOP="$ANDROID_BUILD_TOP"
echo $BUILD_TOP
Changelog=Changelog.txt

DEVICE=$(echo $TARGET_PRODUCT | cut -d "android_")
echo $DEVICE
if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}
for i in $(seq 30);
do
export After_Date=`/bin/date --date="$i days ago" +%F`
k=$(expr $i - 1)
	export Until_Date=`/bin/date --date="$k days ago" +%F`

	# Line with after --- until was too long for a small ListView
	echo '====================' >> $Changelog;
	echo  "     "$Until_Date       >> $Changelog;
	echo '===================='	>> $Changelog;

while read path;
do
    Git_log=`git --git-dir ./${path}/.git log --after=$After_Date --until=$Until_Date --pretty=tformat:"%h  %s  [%an]" --abbrev-commit --abbrev=7`
    if [ ! -z "${Git_log}" ]; then
        echo "\n* ${path}\n${Git_log}\n" >> $Changelog;
    fi
done < ./.repo/project.list;

done
sed -i 's/project/   */g' $Changelog

#~ cp $Changelog $BUILD_TOP/out/target/product/$DEVICE/system/etc/
#~ mv $Changelog $BUILD_TOP/out/target/product/$DEVICE/

#~ cp $Changelog $OUT/system/etc/
#~ cp $Changelog $OUT/
